import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'widgets/glassy_button.dart';

class PrintIcPage extends StatefulWidget {
  const PrintIcPage({super.key});

  @override
  State<PrintIcPage> createState() => _PrintIcPageState();
}

class _PrintIcPageState extends State<PrintIcPage> {
  final _purposeController = TextEditingController();
  DateTime _selectedDate = DateTime.now();
  bool _isGenerating = false;

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2101),
    );
    if (picked != null && picked != _selectedDate) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  Future<void> _generatePdf() async {
    if (_purposeController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a purpose')),
      );
      return;
    }

    setState(() => _isGenerating = true);

    try {
      final doc = pw.Document();
      
      // Load IC Images
      final frontBytes = await rootBundle.load('assets/images/IC.jpg');
      final backBytes = await rootBundle.load('assets/images/icBack.jpg');
      final frontImage = pw.MemoryImage(frontBytes.buffer.asUint8List());
      final backImage = pw.MemoryImage(backBytes.buffer.asUint8List());

      // Load Fonts
      final font = await PdfGoogleFonts.interRegular();
      final fontBold = await PdfGoogleFonts.interBold();

      doc.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          theme: pw.ThemeData.withFont(
            base: font,
            bold: fontBold,
          ),
          build: (pw.Context context) {
            return pw.Stack(
              children: [
                // Watermark Layer
                pw.Center(
                  child: pw.Opacity(
                    opacity: 0.2, // Darker watermark
                    child: pw.Wrap(
                      spacing: 40,
                      runSpacing: 40,
                      children: List.generate(
                        30, 
                        (index) => pw.Transform.rotate(
                          angle: -0.5,
                          child: pw.Text(
                            "${_purposeController.text.toUpperCase()} - ${_selectedDate.toString().split(' ')[0]}",
                            style: pw.TextStyle(
                              fontSize: 16,
                              fontWeight: pw.FontWeight.bold,
                              color: PdfColors.grey600,
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
                
                // Content Layer
                pw.Center(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.center,
                    mainAxisAlignment: pw.MainAxisAlignment.center, // Center vertically
                    children: [
                      pw.Text('IC COPY', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 10),
                      pw.Text('Purpose: ${_purposeController.text}'),
                      pw.Text('Date: ${_selectedDate.toString().split(' ')[0]}'),
                      pw.SizedBox(height: 40),
                      
                      // Front IC Image
                      pw.Container(
                        width: 300,
                        child: pw.Image(frontImage, fit: pw.BoxFit.contain),
                      ),
                      
                      pw.SizedBox(height: 20),
                      
                      // Back IC Image
                      pw.Container(
                        width: 300,
                        child: pw.Image(backImage, fit: pw.BoxFit.contain),
                      ),
                      
                      pw.SizedBox(height: 40),
                      pw.Text('Generated by Journey App', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                    ],
                  ),
                ),
              ],
            );
          },
        ),
      );

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => doc.save(),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error generating PDF: $e')),
      );
    } finally {
      setState(() => _isGenerating = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[50],
      appBar: AppBar(
        title: const Text('Print / Scan IC'),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Generate IC Copy',
              style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            Text(
              'Create a watermarked copy of your IC for official purposes.',
              style: TextStyle(color: Colors.grey[600]),
            ),
            const SizedBox(height: 32),
            
            // Purpose Input
            Text('Purpose', style: TextStyle(fontWeight: FontWeight.w600, color: Colors.grey[800])),
            const SizedBox(height: 8),
            Container(
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.grey[300]!),
              ),
              child: TextField(
                controller: _purposeController,
                decoration: const InputDecoration(
                  hintText: 'e.g. Bank Loan, Telco Registration',
                  border: InputBorder.none,
                  contentPadding: EdgeInsets.all(16),
                ),
              ),
            ),
            
            const SizedBox(height: 24),
            
            // Date Input
            Text('Date', style: TextStyle(fontWeight: FontWeight.w600, color: Colors.grey[800])),
            const SizedBox(height: 8),
            GestureDetector(
              onTap: () => _selectDate(context),
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.grey[300]!),
                ),
                child: Row(
                  children: [
                    Icon(Icons.calendar_today, size: 20, color: Colors.grey[600]),
                    const SizedBox(width: 12),
                    Text(
                      "${_selectedDate.year}-${_selectedDate.month.toString().padLeft(2, '0')}-${_selectedDate.day.toString().padLeft(2, '0')}",
                      style: const TextStyle(fontSize: 16),
                    ),
                  ],
                ),
              ),
            ),
            
            const Spacer(),
            
            GlassyButton(
              onPressed: _isGenerating ? null : _generatePdf,
              child: _isGenerating 
                ? const CircularProgressIndicator(color: Colors.white)
                : const Text('Generate PDF', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            ),
          ],
        ),
      ),
    );
  }
}
